/** Ladle's own settings. The story tree comes from the paths under `src/`. */
export default {
  stories: 'src/**/*.stories.{ts,tsx}',
  defaultStory: 'verification--getting-started--introduction',
  // The guide's own order, so the tree reads the way the sidebar does
  // rather than alphabetically. Generated from src/guide-toc.json; a page
  // the reference adds arrives here and in coverage.mjs together.
  storyOrder: [
    'verification--getting-started--introduction',
    'verification--getting-started--demo',
    'verification--getting-started--installation',
    'verification--getting-started--configuration-options',
    'verification--getting-started--grid-size',
    'verification--getting-started--custom-id-class-and-style',
    'verification--getting-started--license-key',
    'verification--ai-tools--skills-for-claude-code',
    'verification--ai-tools--ai-theme-builder',
    'verification--ai-tools--ai-docs-assistant',
    'verification--styling--themes',
    'verification--styling--design-system',
    'verification--styling--theme-customization',
    'verification--styling--legacy-style',
    'verification--columns--column-headers',
    'verification--columns--column-groups',
    'verification--columns--column-hiding',
    'verification--columns--column-moving',
    'verification--columns--column-freezing',
    'verification--columns--column-widths',
    'verification--columns--column-summary',
    'verification--columns--column-virtualization',
    'verification--columns--column-menu',
    'verification--columns--column-filter',
    'verification--rows--row-headers',
    'verification--rows--row-parent-child',
    'verification--rows--row-hiding',
    'verification--rows--row-moving',
    'verification--rows--row-freezing',
    'verification--rows--row-heights',
    'verification--rows--row-virtualization',
    'verification--rows--rows-sorting',
    'verification--rows--rows-pagination',
    'verification--rows--row-trimming',
    'verification--rows--row-pre-populating',
    'verification--cell-features--selection',
    'verification--cell-features--merge-cells',
    'verification--cell-features--conditional-formatting',
    'verification--cell-features--text-alignment',
    'verification--cell-features--disabled-cells',
    'verification--cell-features--comments',
    'verification--cell-features--autofill-values',
    'verification--cell-features--formatting-cells',
    'verification--cell-functions--cell-functions',
    'verification--cell-functions--cell-renderer',
    'verification--cell-functions--cell-editor',
    'verification--cell-functions--cell-validator',
    'verification--cell-functions--custom-cells',
    'verification--cell-types--cell-type',
    'verification--cell-types--numeric-cell-type',
    'verification--cell-types--date-cell-type',
    'verification--cell-types--time-cell-type',
    'verification--cell-types--checkbox-cell-type',
    'verification--cell-types--select-cell-type',
    'verification--cell-types--dropdown-cell-type',
    'verification--cell-types--autocomplete-cell-type',
    'verification--cell-types--multiselect-cell-type',
    'verification--cell-types--password-cell-type',
    'verification--cell-types--handsontable-cell-type',
    'verification--formulas--installation',
    'verification--formulas--formula-calculation',
    'verification--server-side-data--server-side-data',
    'verification--server-side-data--migrate-to-server-side-data',
    'verification--server-side-data--server-side-configuration',
    'verification--server-side-data--server-side-crud',
    'verification--server-side-data--server-side-fetching-and-examples',
    'verification--data-management--binding-to-data',
    'verification--data-management--saving-data',
    'verification--data-management--events-and-hooks',
    'verification--data-management--export-to-excel',
    'verification--data-management--export-to-csv',
    'verification--data-management--clipboard',
    'verification--accessories-and-menus--context-menu',
    'verification--accessories-and-menus--drag-to-scroll',
    'verification--accessories-and-menus--undo-and-redo',
    'verification--accessories-and-menus--icon-pack',
    'verification--accessories-and-menus--empty-data-state',
    'verification--accessories-and-menus--dialog',
    'verification--accessories-and-menus--loading',
    'verification--accessories-and-menus--notification',
    'verification--accessories-and-menus--layout-slots',
    'verification--internationalization--language',
    'verification--internationalization--locale',
    'verification--internationalization--layout-direction',
    'verification--internationalization--ime-support',
    'verification--accessibility-and-navigation--keyboard-shortcuts',
    'verification--accessibility-and-navigation--custom-shortcuts',
    'verification--accessibility-and-navigation--focus-scopes',
    'verification--accessibility-and-navigation--searching-values',
    'verification--accessibility-and-navigation--accessibility',
    'verification--accessibility-and-navigation--accessibility-conformance-report-vpat',
    'verification--tools-and-building--packages',
    'verification--tools-and-building--modules',
    'verification--tools-and-building--typescript-types',
    'verification--tools-and-building--custom-plugins',
    'verification--tools-and-building--custom-builds',
    'verification--tools-and-building--testing',
    'verification--optimization--batch-operations',
    'verification--optimization--performance',
    'verification--optimization--bundle-size',
    'verification--security--security',
    'verification--technical-specification--supported-browsers',
    'verification--technical-specification--software-license',
    'verification--technical-specification--third-party-licenses',
    'verification--technical-specification--documentation-license',
    'beyond-the-guide--*',
  ],
  addons: {
    a11y: { enabled: true },
    theme: { enabled: true, defaultState: 'light' },
    rtl: { enabled: true },
    width: { enabled: true },
  },
};
